In [3]:
import numpy as np

In [6]:
A = np.array([
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [10, 11, 12]
])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
C = np.random.rand(3, 5)
C

In [5]:
D = np.zeros((2, 4))

In [ ]:
D

In [ ]:
A[1][2]

In [7]:
K = np.array([
              [1],
              [1],
              [1]
])
K

array([[1],
       [1],
       [1]])

In [8]:
A @ K

array([[ 6],
       [15],
       [24],
       [33]])

In [9]:
A * K

ValueError: ignored

In [10]:
P = np.zeros((4, 3))

In [11]:
A * P

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

d

In [ ]:
np.transpose(A)